### ISSUE TITLE
Implement connect, disconnect and reconnet function for WiflyControl

### ISSUE THREAD

**Issue by polybassa** [polybassa/WyLight#104]

**Comment by polybassa** [comment]
use disconnet in WiflyControl.ConfRebootWlanModul, if it's implemented

**Comment by bruenn** [comment]
do we really want to implement these functions? The android app will not need a dedicated connect/disconnect. it will always create a new WiflyControl object, which shouldnt be too expensive compared to the effort we would invest in implement the connected/disconnected state handling.
The difference is: right now without dedicated connect function WiflyControl always acts like it is connected and throws an excption if that assumption was wrong.
If we have a connect function we have to do some if statements to check if it is save to do another connect(). we have to replace some constant member (which might make the creation of the object cheap).

For the android app no explicit connect/disconnect is required, since a WiflyControl object exists only in views which need it.
For example if a setColor fails due a ConnectionTimeout or Lost, android returns to the device selection screen, where no WiflyControl object is necessary. 

Of course it looks expensiv to create a new object for each reconnection, but on the other hand its much cleaner and on a closer look it might be even cheaper than to implement connection handling code in two places and use non constant member.
