### ISSUE TITLE
Clean tracemessages with ostream 

### ISSUE THREAD

**Issue by polybassa** [polybassa/WyLight#52]

**Comment by bruenn** [comment]
I wrote a printf style Trace macro to get rid of our simple Trace_Hex, Trace_Number,... functions, at least in the non pic code. As the PIC compiler is very stupid i think it might be very very difficult to get something similar running on the PIC.
I think it is not a priority to clean up all of our trace code (pic and c++ code). I think it is okay to use printf style Trace() and TraceBuffer() for usage in our c++ code and maybe later refactor it to use c++ streams. In fact the printf style has the advantage that it might be possible to implement a printf for the pic. This wont be easy and shouldnt be a priority but it is a possibility for a homogeneous Trace implementation.
We should rename this issue to "refactor trace code" and set the description to: "1. In non pic code use Trace() and TraceBuffer()  instead of old trace functions.
2. implement printf style trace for pic
